//! Typed RPC/packet event structs, ported field-for-field from `samp/events.lua` +
//! `samp/events/handlers.lua`.
//!
//! Each event is a plain wire-DTO: fields use raw integer/float types (not the domain newtypes) so
//! they map 1:1 onto the reference Lua schema and convert trivially to Lua values. The
//! [`WireDecode`]/[`WireEncode`] traits give every event a uniform body codec; the
//! [`samp_event!`] macro generates the struct, the `RPC_ID`/`EVENT` constants, and both trait impls
//! from a declarative field list.
//!
//! Events whose layout is content-dependent (give/take damage, object material vs. text) or that
//! read to the end of the stream (scores/pings, weapons update, create-object materials) are hand
//! written in the submodules rather than via the macro.
//!
//! # Why raw primitives, not the domain newtypes
//!
//! Event fields use `u16`/`i32`/`f32` rather than [`crate::PlayerId`] & friends *by policy*: these
//! are wire DTOs at the decode boundary. Raw ints make decoding tolerant of unknown/forward-compat
//! values a stricter type would reject, and map 1:1 onto both the reference Lua schema and the Lua
//! tables the bridge produces. Promotion to the domain newtypes (and closed enums for `reason`,
//! `style`, `special_action`, …) belongs in a DTO→domain conversion layer above this module, not in
//! the wire structs themselves.

use std::collections::HashMap;
use std::sync::OnceLock;

use crate::bitstream::{BitStreamReader, BitStreamWriter};
use crate::{Quaternion, Result, Vector2, Vector3};

pub mod incoming_rpc;
pub mod incoming_rpc_b;
pub mod incoming_rpc_c;
pub mod outgoing_rpc;

/// A single decoded event field, in the order it appears on the wire. This is the dynamic bridge
/// between the typed event structs and the script layer: an event decodes to an ordered
/// `Vec<FieldValue>` (the positional callback arguments), and a script's (possibly mutated) values
/// re-encode through the same event. One `match` in the script host converts these to/from Lua,
/// rather than 152 per-struct conversions.
#[derive(Debug, Clone, PartialEq)]
pub enum FieldValue {
    Bool(bool),
    U8(u8),
    U16(u16),
    U32(u32),
    I8(i8),
    I16(i16),
    I32(i32),
    F32(f32),
    Vec3(Vector3),
    Vec2(Vector2),
    Quat(Quaternion),
    /// `str8`/`str16`/`str32`/`fixedString` — raw bytes in the server encoding.
    Bytes(Vec<u8>),
    IntArray3([i32; 3]),
}

/// Dynamic conversion between a typed event and its positional [`FieldValue`] list, plus the id and
/// MoonLoader event name. Generated by [`samp_event!`]; the registry erases the concrete type behind
/// function pointers so the host can decode by id.
pub trait EventConv: WireDecode + WireEncode + Sized {
    const RPC_ID: u8;
    const EVENT: &'static str;

    /// The event's fields as positional values, in wire order.
    fn to_values(&self) -> Vec<FieldValue>;

    /// Rebuild the event from positional values (a script's rewritten arguments). Errors on an
    /// arity or type mismatch.
    fn from_values(values: &[FieldValue]) -> Result<Self>;

    /// Decode a payload straight to its positional values.
    fn decode_values(payload: &[u8]) -> Result<Vec<FieldValue>> {
        Ok(decode_event::<Self>(payload)?.to_values())
    }

    /// Encode positional values straight to a payload.
    fn encode_values(values: &[FieldValue]) -> Result<Vec<u8>> {
        Ok(encode_event(&Self::from_values(values)?))
    }
}

/// An event tagged with its wire direction, so a registry can route `register::<T>` without a
/// direction argument. Implemented by the [`incoming_event!`]/[`outgoing_event!`] macros.
pub trait DirectedEvent: EventConv {
    const DIRECTION: crate::Direction;
}

/// Decode an event body from the argument bitstream (the id byte is already stripped).
pub trait WireDecode: Sized {
    fn decode(r: &mut BitStreamReader) -> Result<Self>;
}

/// Encode an event body back to a bitstream (used when a script rewrites a packet).
pub trait WireEncode {
    fn encode(&self, w: &mut BitStreamWriter);
}

/// Decode an event directly from a payload slice.
pub fn decode_event<T: WireDecode>(payload: &[u8]) -> Result<T> {
    let mut r = BitStreamReader::new(payload);
    T::decode(&mut r)
}

/// Encode an event to a fresh payload buffer.
pub fn encode_event<T: WireEncode>(event: &T) -> Vec<u8> {
    let mut w = BitStreamWriter::new();
    event.encode(&mut w);
    w.into_bytes()
}

// The three macros below (`read_field!`, `write_field!`, `field_ty!`) enumerate the same wire-type
// tokens in lockstep — adding or renaming a wire type means editing all three. Keep them in sync.
macro_rules! read_field {
    ($r:ident, bool) => {
        $r.read_bit()?
    };
    ($r:ident, bool8) => {
        $r.read_bool8()?
    };
    ($r:ident, bool32) => {
        $r.read_bool32()?
    };
    ($r:ident, u8) => {
        $r.read_u8()?
    };
    ($r:ident, u16) => {
        $r.read_u16()?
    };
    ($r:ident, u32) => {
        $r.read_u32()?
    };
    ($r:ident, i8) => {
        $r.read_i8()?
    };
    ($r:ident, i16) => {
        $r.read_i16()?
    };
    ($r:ident, i32) => {
        $r.read_i32()?
    };
    ($r:ident, f32) => {
        $r.read_f32()?
    };
    ($r:ident, vector3) => {
        $r.read_vector3()?
    };
    ($r:ident, vector2) => {
        $r.read_vector2()?
    };
    ($r:ident, norm_quat) => {
        $r.read_norm_quat()?
    };
    ($r:ident, compressed_vector) => {
        $r.read_compressed_vector()?
    };
    ($r:ident, str8) => {
        $r.read_str8_bytes()?
    };
    ($r:ident, str16) => {
        $r.read_str16()?
    };
    ($r:ident, str32) => {
        $r.read_str32()?
    };
    ($r:ident, fixed32) => {
        $r.read_fixed_string(32)?
    };
    ($r:ident, int_array3) => {
        [$r.read_i32()?, $r.read_i32()?, $r.read_i32()?]
    };
}

macro_rules! write_field {
    ($w:ident, $v:expr, bool) => {
        $w.write_bit($v)
    };
    ($w:ident, $v:expr, bool8) => {
        $w.write_bool8($v)
    };
    ($w:ident, $v:expr, bool32) => {
        $w.write_bool32($v)
    };
    ($w:ident, $v:expr, u8) => {
        $w.write_u8($v)
    };
    ($w:ident, $v:expr, u16) => {
        $w.write_u16($v)
    };
    ($w:ident, $v:expr, u32) => {
        $w.write_u32($v)
    };
    ($w:ident, $v:expr, i8) => {
        $w.write_i8($v)
    };
    ($w:ident, $v:expr, i16) => {
        $w.write_i16($v)
    };
    ($w:ident, $v:expr, i32) => {
        $w.write_i32($v)
    };
    ($w:ident, $v:expr, f32) => {
        $w.write_f32($v)
    };
    ($w:ident, $v:expr, vector3) => {
        $w.write_vector3($v)
    };
    ($w:ident, $v:expr, vector2) => {
        $w.write_vector2($v)
    };
    ($w:ident, $v:expr, norm_quat) => {
        $w.write_norm_quat($v)
    };
    ($w:ident, $v:expr, compressed_vector) => {
        $w.write_compressed_vector($v)
    };
    ($w:ident, $v:expr, str8) => {
        $w.write_str8_bytes(&$v)
    };
    ($w:ident, $v:expr, str16) => {
        $w.write_str16(&$v)
    };
    ($w:ident, $v:expr, str32) => {
        $w.write_str32(&$v)
    };
    ($w:ident, $v:expr, fixed32) => {
        $w.write_fixed_string(&$v, 32)
    };
    ($w:ident, $v:expr, int_array3) => {{
        for x in &$v {
            $w.write_i32(*x);
        }
    }};
}

macro_rules! field_ty {
    (bool) => { bool };
    (bool8) => { bool };
    (bool32) => { bool };
    (u8) => { u8 };
    (u16) => { u16 };
    (u32) => { u32 };
    (i8) => { i8 };
    (i16) => { i16 };
    (i32) => { i32 };
    (f32) => { f32 };
    (vector3) => { $crate::Vector3 };
    (vector2) => { $crate::Vector2 };
    (norm_quat) => { $crate::Quaternion };
    (compressed_vector) => { $crate::Vector3 };
    (str8) => { Vec<u8> };
    (str16) => { Vec<u8> };
    (str32) => { Vec<u8> };
    (fixed32) => { Vec<u8> };
    (int_array3) => { [i32; 3] };
}

// `to_value!`/`from_value!` map between a struct field and its [`FieldValue`]. Like the codec
// macros above, these enumerate the wire tokens in lockstep — keep them in sync with `field_ty!`.
macro_rules! to_value {
    ($v:expr, bool) => {
        $crate::events::FieldValue::Bool($v)
    };
    ($v:expr, bool8) => {
        $crate::events::FieldValue::Bool($v)
    };
    ($v:expr, bool32) => {
        $crate::events::FieldValue::Bool($v)
    };
    ($v:expr, u8) => {
        $crate::events::FieldValue::U8($v)
    };
    ($v:expr, u16) => {
        $crate::events::FieldValue::U16($v)
    };
    ($v:expr, u32) => {
        $crate::events::FieldValue::U32($v)
    };
    ($v:expr, i8) => {
        $crate::events::FieldValue::I8($v)
    };
    ($v:expr, i16) => {
        $crate::events::FieldValue::I16($v)
    };
    ($v:expr, i32) => {
        $crate::events::FieldValue::I32($v)
    };
    ($v:expr, f32) => {
        $crate::events::FieldValue::F32($v)
    };
    ($v:expr, vector3) => {
        $crate::events::FieldValue::Vec3($v)
    };
    ($v:expr, vector2) => {
        $crate::events::FieldValue::Vec2($v)
    };
    ($v:expr, norm_quat) => {
        $crate::events::FieldValue::Quat($v)
    };
    ($v:expr, compressed_vector) => {
        $crate::events::FieldValue::Vec3($v)
    };
    ($v:expr, str8) => {
        $crate::events::FieldValue::Bytes($v.clone())
    };
    ($v:expr, str16) => {
        $crate::events::FieldValue::Bytes($v.clone())
    };
    ($v:expr, str32) => {
        $crate::events::FieldValue::Bytes($v.clone())
    };
    ($v:expr, fixed32) => {
        $crate::events::FieldValue::Bytes($v.clone())
    };
    ($v:expr, int_array3) => {
        $crate::events::FieldValue::IntArray3($v)
    };
}

macro_rules! from_value {
    ($opt:expr, bool) => { from_value!(@b $opt) };
    ($opt:expr, bool8) => { from_value!(@b $opt) };
    ($opt:expr, bool32) => { from_value!(@b $opt) };
    ($opt:expr, u8) => { match $opt { Some($crate::events::FieldValue::U8(x)) => Ok(*x), _ => Err($crate::ProtoError::Malformed("rpc field type/arity mismatch")) }? };
    ($opt:expr, u16) => { match $opt { Some($crate::events::FieldValue::U16(x)) => Ok(*x), _ => Err($crate::ProtoError::Malformed("rpc field type/arity mismatch")) }? };
    ($opt:expr, u32) => { match $opt { Some($crate::events::FieldValue::U32(x)) => Ok(*x), _ => Err($crate::ProtoError::Malformed("rpc field type/arity mismatch")) }? };
    ($opt:expr, i8) => { match $opt { Some($crate::events::FieldValue::I8(x)) => Ok(*x), _ => Err($crate::ProtoError::Malformed("rpc field type/arity mismatch")) }? };
    ($opt:expr, i16) => { match $opt { Some($crate::events::FieldValue::I16(x)) => Ok(*x), _ => Err($crate::ProtoError::Malformed("rpc field type/arity mismatch")) }? };
    ($opt:expr, i32) => { match $opt { Some($crate::events::FieldValue::I32(x)) => Ok(*x), _ => Err($crate::ProtoError::Malformed("rpc field type/arity mismatch")) }? };
    ($opt:expr, f32) => { match $opt { Some($crate::events::FieldValue::F32(x)) => Ok(*x), _ => Err($crate::ProtoError::Malformed("rpc field type/arity mismatch")) }? };
    ($opt:expr, vector3) => { match $opt { Some($crate::events::FieldValue::Vec3(x)) => Ok(*x), _ => Err($crate::ProtoError::Malformed("rpc field type/arity mismatch")) }? };
    ($opt:expr, compressed_vector) => { match $opt { Some($crate::events::FieldValue::Vec3(x)) => Ok(*x), _ => Err($crate::ProtoError::Malformed("rpc field type/arity mismatch")) }? };
    ($opt:expr, vector2) => { match $opt { Some($crate::events::FieldValue::Vec2(x)) => Ok(*x), _ => Err($crate::ProtoError::Malformed("rpc field type/arity mismatch")) }? };
    ($opt:expr, norm_quat) => { match $opt { Some($crate::events::FieldValue::Quat(x)) => Ok(*x), _ => Err($crate::ProtoError::Malformed("rpc field type/arity mismatch")) }? };
    ($opt:expr, str8) => { from_value!(@bytes $opt) };
    ($opt:expr, str16) => { from_value!(@bytes $opt) };
    ($opt:expr, str32) => { from_value!(@bytes $opt) };
    ($opt:expr, fixed32) => { from_value!(@bytes $opt) };
    ($opt:expr, int_array3) => { match $opt { Some($crate::events::FieldValue::IntArray3(x)) => Ok(*x), _ => Err($crate::ProtoError::Malformed("rpc field type/arity mismatch")) }? };
    (@b $opt:expr) => { match $opt { Some($crate::events::FieldValue::Bool(x)) => Ok(*x), _ => Err($crate::ProtoError::Malformed("rpc field type/arity mismatch")) }? };
    (@bytes $opt:expr) => { match $opt { Some($crate::events::FieldValue::Bytes(x)) => Ok(x.clone()), _ => Err($crate::ProtoError::Malformed("rpc field type/arity mismatch")) }? };
}

/// Generate an event struct + its `RPC_ID`/`EVENT` constants + [`WireDecode`]/[`WireEncode`] from a
/// declarative field list. Field type tokens map to the SA-MP wire primitives (see [`read_field!`]).
macro_rules! samp_event {
    (
        $(#[$meta:meta])*
        $name:ident = $id:literal, $ev:literal {
            $( $field:ident : $fty:tt ),* $(,)?
        }
    ) => {
        $(#[$meta])*
        #[derive(Debug, Clone, PartialEq)]
        pub struct $name {
            $( pub $field: field_ty!($fty), )*
        }

        impl $name {
            /// SA-MP RPC/packet id this event is carried by.
            pub const RPC_ID: u8 = $id;
            /// MoonLoader-compatible event name (the Lua callback key).
            pub const EVENT: &'static str = $ev;
        }

        impl $crate::events::WireDecode for $name {
            #[allow(unused_variables)]
            fn decode(r: &mut $crate::BitStreamReader) -> $crate::Result<Self> {
                Ok(Self {
                    $( $field: read_field!(r, $fty), )*
                })
            }
        }

        impl $crate::events::WireEncode for $name {
            #[allow(unused_variables)]
            fn encode(&self, w: &mut $crate::BitStreamWriter) {
                $( write_field!(w, self.$field, $fty); )*
            }
        }

        impl $crate::events::EventConv for $name {
            const RPC_ID: u8 = $id;
            const EVENT: &'static str = $ev;

            fn to_values(&self) -> ::std::vec::Vec<$crate::events::FieldValue> {
                ::std::vec![ $( to_value!(self.$field, $fty), )* ]
            }

            #[allow(unused_variables, unused_mut)]
            fn from_values(values: &[$crate::events::FieldValue]) -> $crate::Result<Self> {
                let mut iter = values.iter();
                Ok(Self {
                    $( $field: from_value!(iter.next(), $fty), )*
                })
            }
        }
    };
}

/// Like [`samp_event!`] but also registers the event in the incoming (server→client) dispatch table.
/// The `@register` arm is listed first so the recursive marker call never falls through to the
/// general arm (which would re-expand and recurse).
macro_rules! incoming_event {
    (@register $(#[$meta:meta])* $name:ident = $($rest:tt)* ) => {
        impl $crate::events::DirectedEvent for $name {
            const DIRECTION: $crate::Direction = $crate::Direction::Incoming;
        }
        $crate::inventory::submit! {
            $crate::events::IncomingDescriptor($crate::events::make_descriptor::<$name>)
        }
    };
    ( $($def:tt)* ) => {
        samp_event! { $($def)* }
        incoming_event!(@register $($def)*);
    };
}

/// Like [`samp_event!`] but also registers the event in the outgoing (client→server) dispatch table.
macro_rules! outgoing_event {
    (@register $(#[$meta:meta])* $name:ident = $($rest:tt)* ) => {
        impl $crate::events::DirectedEvent for $name {
            const DIRECTION: $crate::Direction = $crate::Direction::Outgoing;
        }
        $crate::inventory::submit! {
            $crate::events::OutgoingDescriptor($crate::events::make_descriptor::<$name>)
        }
    };
    ( $($def:tt)* ) => {
        samp_event! { $($def)* }
        outgoing_event!(@register $($def)*);
    };
}

pub(crate) use {
    field_ty, from_value, incoming_event, outgoing_event, read_field, samp_event, to_value,
    write_field,
};

/// A type-erased view of one event: its id, name, and the decode/encode function pointers. Built
/// once per event type via [`make_descriptor`] and collected into the dispatch registries.
#[derive(Clone, Copy)]
pub struct EventDescriptor {
    pub rpc_id: u8,
    pub event: &'static str,
    pub decode: fn(&[u8]) -> Result<Vec<FieldValue>>,
    pub encode: fn(&[FieldValue]) -> Result<Vec<u8>>,
}

/// Construct the descriptor for an event type. Exposed (not private) so the registration macros can
/// name it as a `fn`-pointer in the `inventory::submit!` static.
pub fn make_descriptor<T: EventConv + 'static>() -> EventDescriptor {
    EventDescriptor {
        rpc_id: T::RPC_ID,
        event: T::EVENT,
        decode: T::decode_values,
        encode: T::encode_values,
    }
}

/// `inventory` wrappers — each carries a constructor so registration stays a plain function pointer
/// in a `static` (no const-generic evaluation), and incoming/outgoing share no id space.
pub struct IncomingDescriptor(pub fn() -> EventDescriptor);
pub struct OutgoingDescriptor(pub fn() -> EventDescriptor);
inventory::collect!(IncomingDescriptor);
inventory::collect!(OutgoingDescriptor);

fn build_registry(
    descriptors: impl Iterator<Item = EventDescriptor>,
) -> HashMap<u8, EventDescriptor> {
    let mut map = HashMap::new();
    for descriptor in descriptors {
        let previous = map.insert(descriptor.rpc_id, descriptor);
        debug_assert!(
            previous.is_none(),
            "duplicate RPC id {} in dispatch registry",
            descriptor.rpc_id
        );
    }
    map
}

fn incoming_registry() -> &'static HashMap<u8, EventDescriptor> {
    static REGISTRY: OnceLock<HashMap<u8, EventDescriptor>> = OnceLock::new();
    REGISTRY.get_or_init(|| {
        build_registry(
            inventory::iter::<IncomingDescriptor>
                .into_iter()
                .map(|d| (d.0)()),
        )
    })
}

fn outgoing_registry() -> &'static HashMap<u8, EventDescriptor> {
    static REGISTRY: OnceLock<HashMap<u8, EventDescriptor>> = OnceLock::new();
    REGISTRY.get_or_init(|| {
        build_registry(
            inventory::iter::<OutgoingDescriptor>
                .into_iter()
                .map(|d| (d.0)()),
        )
    })
}

/// Decode an incoming RPC body to `(eventName, positionalValues)`, or `None` if the id is not a
/// known fixed-layout event. The inner `Result` reports a malformed body.
pub fn decode_incoming(id: u8, payload: &[u8]) -> Option<Result<(&'static str, Vec<FieldValue>)>> {
    let descriptor = incoming_registry().get(&id)?;
    Some((descriptor.decode)(payload).map(|values| (descriptor.event, values)))
}

/// Re-encode an incoming RPC body from positional values (a script rewrite). `None` if unknown id.
pub fn encode_incoming(id: u8, values: &[FieldValue]) -> Option<Result<Vec<u8>>> {
    let descriptor = incoming_registry().get(&id)?;
    Some((descriptor.encode)(values))
}

/// Decode an outgoing RPC body to `(eventName, positionalValues)`. `None` if unknown id.
pub fn decode_outgoing(id: u8, payload: &[u8]) -> Option<Result<(&'static str, Vec<FieldValue>)>> {
    let descriptor = outgoing_registry().get(&id)?;
    Some((descriptor.decode)(payload).map(|values| (descriptor.event, values)))
}

/// Re-encode an outgoing RPC body from positional values. `None` if unknown id.
pub fn encode_outgoing(id: u8, values: &[FieldValue]) -> Option<Result<Vec<u8>>> {
    let descriptor = outgoing_registry().get(&id)?;
    Some((descriptor.encode)(values))
}

#[cfg(test)]
mod dispatch_tests;
